### ISSUE TITLE
强迫症犯了……

### ISSUE THREAD

**Issue by myst729** [easychen/vue-starter#1]
大小写不一样
![image](https://cloud.githubusercontent.com/assets/519733/11329340/d956ed16-91d5-11e5-84e6-020f4629f2ff.png)

大括号不一样，参数列表空格不一样
![image](https://cloud.githubusercontent.com/assets/519733/11329347/ef044762-91d5-11e5-974a-aa8747b5b9a4.png)

**Comment by easychen** [comment]
看不惯提PR进来 嘿嘿
